FROM registry.fedoraproject.org/fedora-toolbox:44@sha256:19bb94eec64b3ff4910bd782bb8b603ee0c010a529f125f06afed94fc213f684

RUN \
    dnf config-manager disable \
        fedora-cisco-openh264 \
    && \
    dnf --assumeyes install \
        adw-gtk3-theme \
        flatpak-xdg-utils \
    && \
    dnf --assumeyes install \
        emacs-pgtk \
        ripgrep \
        fd-find \
    && \
    dnf --assumeyes install \
        cmake \
        go \
        gopls \
        hunspell \
        hunspell-en-US \
        hunspell-fr \
        libtool \
        nodejs-bash-language-server \
        nodejs-npm \
        pandoc \
        shfmt \
        wl-clipboard \
    && \
    dnf clean all && \
    ln -sf /usr/bin/flatpak-xdg-open /usr/bin/xdg-open
