FROM registry.fedoraproject.org/fedora-toolbox:44@sha256:5115e16dced45e1cfbaaf1c1423e524c3f5b0585ed9f1a98b9db799af295c4a3

RUN --mount=type=tmpfs,target=/var << 'EOF'
set -e -o nounset -o pipefail
set -x

dnf config-manager disable \
    fedora-cisco-openh264 \


dnf --assumeyes install \
    adw-gtk3-theme \
    flatpak-xdg-utils \


dnf --assumeyes install \
    emacs-pgtk \
    ripgrep \
    fd-find \
    gdouros-symbola-fonts \


dnf --assumeyes install \
    cmake \
    go \
    gopls \
    hunspell \
    hunspell-en-US \
    hunspell-fr \
    libtool \
    nodejs-bash-language-server \
    nodejs-npm \
    pandoc \
    shfmt \
    wl-clipboard \


dnf clean all

ln -sf /usr/bin/flatpak-xdg-open /usr/bin/xdg-open
EOF
