FROM registry.fedoraproject.org/fedora-toolbox:44@sha256:9631027b164ae98aa71fe1a8e88a214ca953177756a5da08bfe9f92531f60d93

RUN --mount=type=tmpfs,target=/var << 'EOF'
set -e -o nounset -o pipefail
set -x

dnf config-manager disable \
    fedora-cisco-openh264 \


dnf --assumeyes install \
    adw-gtk3-theme \
    flatpak-xdg-utils \


dnf --assumeyes install \
    emacs-pgtk \
    ripgrep \
    fd-find \
    gdouros-symbola-fonts \


dnf --assumeyes install \
    cmake \
    go \
    gopls \
    hunspell \
    hunspell-en-US \
    hunspell-fr \
    libtool \
    nodejs-bash-language-server \
    nodejs-npm \
    pandoc \
    shfmt \
    wl-clipboard \


dnf clean all

ln -sf /usr/bin/flatpak-xdg-open /usr/bin/xdg-open
EOF
