name: reusable-build
on:
  workflow_call:
    inputs:
      registry:
        type: string
        required: true
      repository:
        type: string
        required: true
      tags:
        type: string
        required: true
      containerfile:
        default: ${{ forgejo.workspace }}/Containerfile
        type: string
        required: false
      context:
        default: ${{ forgejo.workspace }}
        type: string
        required: false
      containers-policy:
        type: string
        required: false
      podman-log-level:
        default: 'warn' # debug, info, warn, error, fatal or panic (default: warn)
        type: string
        required: false

env:
  SOURCE: ${{ forgejo.event.repository.html_url }}
  REGISTRY: ${{ inputs.registry }}
  REPOSITORY: ${{ inputs.repository }}
  TAGS: ${{ inputs.tags }}
  CONTAINERFILE: ${{ inputs.containerfile }}
  CONTEXT: ${{ inputs.context }}
  CONTAINERS_POLICY: ${{ inputs.containers-policy }}
  LOG_LEVEL: ${{ inputs.podman-log-level }}

jobs:
  reusable-build:
    name: reusable-build
    runs-on: podman-builder

    steps:
      - name: checkout
        uses: https://code.forgejo.org/actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

      - name: change containers signature policy
        shell: bash --noprofile --norc -e -o nounset -o pipefail {0}
        run: |
          mkdir -p "${HOME}/.config/containers/registries.d"

          cat << EOF > "${HOME}/.config/containers/registries.d/default-docker.yaml"
          default-docker:
            use-sigstore-attachments: true
          EOF

          if [ -n "${CONTAINERS_POLICY}" ]; then
            cp "${CONTAINERS_POLICY}" "${HOME}/.config/containers/policy.json"
            cat "${HOME}/.config/containers/policy.json"
          fi

      - name: build
        id: build
        shell: bash --noprofile --norc -e -o nounset -o pipefail {0}
        run: |
          labels=()
          tags=()
          image_with_tag=''

          labels+=( '--label' "org.opencontainers.image.source=${SOURCE}" )

          for tag in ${TAGS}; do
            tags+=( '--tag' "${REGISTRY}/${REPOSITORY}:${tag}" )
            if [ -z "${image_with_tag}" ]; then
              image_with_tag="${REGISTRY}/${REPOSITORY}:${tag}"
            fi
          done

          buildah --log-level "${LOG_LEVEL}" bud --format oci --file "${CONTAINERFILE}" "${labels[@]}" "${tags[@]}" "${CONTEXT}"

          {
            printf 'image-with-tag=%s\n' "${image_with_tag}"
          } >> "${FORGEJO_OUTPUT}"

      - name: perform static analysis checks (bootc images)
        shell: bash --noprofile --norc -e -o nounset -o pipefail {0}
        run: |
          for tag in ${TAGS}; do
            if podman image inspect "${REGISTRY}/${REPOSITORY}:${tag}" | jq -e '.[].Config.Labels["containers.bootc"] == "1"' >/dev/null; then
              podman --log-level "${LOG_LEVEL}" run --rm "${REGISTRY}/${REPOSITORY}:${tag}" bootc container lint --fatal-warnings
            fi
          done

      - name: login to container registry
        id: login
        if: ${{ forgejo.event_name != 'pull_request' && forgejo.ref == 'refs/heads/main' }}
        env:
          REGISTRY_USER: ${{ secrets.registry-user }}
          REGISTRY_PASSWORD: ${{ secrets.registry-password }}
        shell: bash --noprofile --norc -e -o nounset -o pipefail {0}
        run: |
          podman --log-level "${LOG_LEVEL}" login --username "${REGISTRY_USER}" --password "${REGISTRY_PASSWORD}" "${REGISTRY}"

      - name: push to registry
        id: push
        if: ${{ forgejo.event_name != 'pull_request' && forgejo.ref == 'refs/heads/main' }}
        env:
          SIGSTORE_PRIVATE_KEY: ${{ secrets.sigstore-private-key }}
        shell: bash --noprofile --norc -e -o nounset -o pipefail {0}
        run: |
          for tag in ${TAGS}; do
            podman --log-level "${LOG_LEVEL}" push --sign-by-sigstore-private-key <(printf '%s\n' "${SIGSTORE_PRIVATE_KEY}") "${REGISTRY}/${REPOSITORY}:${tag}"
          done

      - name: logout from container registry
        if: ${{ always() && (steps.login.outcome == 'success' || steps.login.outcome == 'failure' ) }}
        shell: bash --noprofile --norc -e -o nounset -o pipefail {0}
        run: |
          podman --log-level "${LOG_LEVEL}" logout "${REGISTRY}"
