name: reusable-build
on:
  workflow_call:
    inputs:
      image-names:
        type: string
        required: true
      containerfiles:
        type: string
        required: false
      labels:
        type: string
        required: false
      context:
        type: string
        required: false
      source:
        default: ${{ forgejo.event.repository.html_url }}
        type: string
        required: false
      push:
        default: ${{ forgejo.event_name != 'pull_request' && forgejo.ref == 'refs/heads/main' }}
        type: boolean
        required: false
      containers-policy:
        type: string
        required: false
      podman-log-level:
        default: 'warn' # debug, info, warn, error, fatal or panic (default: warn)
        type: string
        required: false

env:
  IMAGE_NAMES: ${{ inputs.image-names }}
  CONTAINERFILES: ${{ inputs.containerfiles }}
  LABELS: ${{ inputs.labels }}
  CONTEXT: ${{ inputs.context }}
  SOURCE: ${{ inputs.source }}
  CONTAINERS_POLICY: ${{ inputs.containers-policy }}
  LOG_LEVEL: ${{ inputs.podman-log-level }}

jobs:
  reusable-build:
    name: reusable-build
    runs-on: podman-builder

    steps:
      - name: checkout
        uses: https://code.forgejo.org/actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

      - name: change containers signature policy
        shell: bash --noprofile --norc -e -o nounset -o pipefail {0}
        run: |
          mkdir -p "${HOME}/.config/containers/registries.d"

          cat << EOF > "${HOME}/.config/containers/registries.d/default-docker.yaml"
          default-docker:
            use-sigstore-attachments: true
          EOF

          if [ -n "${CONTAINERS_POLICY}" ]; then
            cp "${CONTAINERS_POLICY}" "${HOME}/.config/containers/policy.json"
            cat "${HOME}/.config/containers/policy.json"
          fi

      - name: build
        id: build
        shell: bash --noprofile --norc -e -o nounset -o pipefail {0}
        run: |
          args=()

          for image_name in ${IMAGE_NAMES}; do
            args+=( '--tag' "${image_name}" )
          done

          for containerfile in ${CONTAINERFILES}; do
            args+=( '--file' "${containerfile}" )
          done

          args+=( '--label' "org.opencontainers.image.source=${SOURCE}" )

          for label in ${LABELS}; do
            args+=( '--label' "${label}" )
          done

          buildah --log-level "${LOG_LEVEL}" build \
            --format oci \
            "${args[@]}" \
            "${CONTEXT}"

      - name: perform static analysis checks (bootc images)
        shell: bash --noprofile --norc -e -o nounset -o pipefail {0}
        run: |
          for image_name in ${IMAGE_NAMES}; do
            if podman image inspect "${image_name}" |
                jq -e '.[].Config.Labels["containers.bootc"] == "1"' >/dev/null; then
              podman --log-level "${LOG_LEVEL}" run \
                --rm \
                "${image_name}" \
                bootc container lint --fatal-warnings
              fi
          done

      - name: push
        id: push
        if: ${{ inputs.push }}
        env:
          REGISTRY_USER: ${{ secrets.registry-user }}
          REGISTRY_PASSWORD: ${{ secrets.registry-password }}
          SIGSTORE_PRIVATE_KEY: ${{ secrets.sigstore-private-key }}
          SIGSTORE_PASSPHRASE: ${{ secrets.sigstore-passphrase }}
        shell: bash --noprofile --norc -e -o nounset -o pipefail {0}
        run: |
          args=()

          if [ -n "${REGISTRY_USER}" ] && [ -n "${REGISTRY_PASSWORD}" ]; then
            args+=( '--creds' "${REGISTRY_USER}:${REGISTRY_PASSWORD}" )
          fi

          if [ -n "${SIGSTORE_PRIVATE_KEY}" ]; then
            for image_name in ${IMAGE_NAMES}; do
              podman --log-level "${LOG_LEVEL}" push \
                "${args[@]}" \
                --sign-by-sigstore-private-key <(printf '%s\n' "${SIGSTORE_PRIVATE_KEY}") \
                --sign-passphrase-file <(printf '%s\n' "${SIGSTORE_PASSPHRASE}") \
                "${image_name}"
            done
          else
            for image_name in ${IMAGE_NAMES}; do
              podman --log-level "${LOG_LEVEL}" push \
                "${args[@]}" \
                "${image_name}"
            done
          fi

      - name: logout from container registry
        if: ${{ always() }}
        shell: bash --noprofile --norc -e -o nounset -o pipefail {0}
        run: |
          podman --log-level "${LOG_LEVEL}" logout \
            --all
