FROM registry.fedoraproject.org/fedora-toolbox:44@sha256:52433f3bc57045ed743a247edda98c8732a2c0ed37a1c3a28a72ea980095e743

RUN \
    dnf config-manager disable \
        fedora-cisco-openh264 \
    && \
    dnf --assumeyes install \
        adw-gtk3-theme \
        flatpak-xdg-utils \
    && \
    dnf --assumeyes install \
        fzf \
        mpv \
        stow \
    && \
    dnf clean all && \
    ln -sf /usr/bin/flatpak-xdg-open /usr/bin/xdg-open
