FROM registry.fedoraproject.org/fedora-toolbox:44@sha256:1be20dec96d2d31532f05e4deb7e2d5a9a745648686eb0f500d9734289e8081d

RUN --mount=type=tmpfs,target=/var << 'EOF'
set -e -o nounset -o pipefail
set -x

dnf config-manager disable \
    fedora-cisco-openh264 \


dnf --assumeyes install \
    adw-gtk3-theme \
    flatpak-xdg-utils \


dnf --assumeyes install \
    emacs-pgtk \
    ripgrep \
    fd-find \


dnf --assumeyes install \
    fzf \
    mpv \
    stow \


dnf clean all

ln -sf /usr/bin/flatpak-xdg-open /usr/bin/xdg-open
EOF
