FROM registry.fedoraproject.org/fedora-toolbox:42

RUN sed -i "s/enabled=1/enabled=0/" /etc/yum.repos.d/fedora-cisco-openh264.repo && \
    dnf5 --assumeyes install \
        adw-gtk3-theme \
    && \
    dnf5 --assumeyes install \
        fzf \
        mpv \
        stow \
    && \
    dnf5 clean all
