FROM forgejo.clmnt.xyz/clmnt/podman:latest@sha256:7f226be6a1e840b990eda79168b2faa31d0a44b44a9392e0a44d260ceaeaa511

RUN --mount=type=tmpfs,target=/var << 'EOF'
set -e -o nounset -o pipefail
set -x

dnf --assumeyes --setopt=install_weak_deps=False install \
    git-core \
    nodejs24 \


dnf --assumeyes --setopt=install_weak_deps=False install \
    buildah \
    skopeo \
    jq \


dnf clean all
EOF
