FROM forgejo.clmnt.xyz/clmnt/podman:latest@sha256:5a3528a587ff66c40b761ac6eab4684b394819a59df25825617d64d0e03ac50a

RUN --mount=type=tmpfs,target=/var << 'EOF'
set -e -o nounset -o pipefail
set -x

dnf --assumeyes --setopt=install_weak_deps=False install \
    git-core \
    nodejs24 \


dnf --assumeyes --setopt=install_weak_deps=False install \
    buildah \
    skopeo \
    jq \


dnf clean all
EOF
