FROM registry.fedoraproject.org/fedora:44@sha256:c728541e20af014cf4752fc21225d290ed08bd3fa905f303c7596f056bfdb03c

RUN --mount=type=tmpfs,target=/var << 'EOR'
set -e -o nounset -o pipefail
set -x

sed -i "/enabled=/s/1/0/" \
    /etc/yum.repos.d/fedora-cisco-openh264.repo \

rpm --setcaps shadow-utils

dnf --assumeyes --setopt=install_weak_deps=False install \
    --exclude container-selinux \
    podman \


dnf clean all

useradd --uid 1000 podman
printf 'root:1:65535\npodman:1:999\npodman:1001:64535\n' > /etc/subuid
printf 'root:1:65535\npodman:1:999\npodman:1001:64535\n' > /etc/subgid

cat << 'EOF' > /etc/containers/containers.conf
[containers]
netns="host"
userns="host"
ipcns="host"
utsns="host"
cgroupns="host"
cgroups="disabled"
log_driver = "k8s-file"
[engine]
cgroup_manager = "cgroupfs"
events_logger="file"
runtime="crun"
EOF

if [ -f /etc/containers/storage.conf ]; then
    sed -i -e '/mountopt =/s/".*"/"nodev"/' \
    /etc/containers/storage.conf
else
    sed -e '/mountopt =/s/".*"/"nodev"/' \
    /usr/share/containers/storage.conf > /etc/containers/storage.conf
fi


mkdir -p /home/podman/.config/containers/
cat << 'EOF' > /home/podman/.config/containers/containers.conf
[containers]
volumes = [
    "/proc:/proc",
]
default_sysctls = []
EOF

mkdir -p /home/podman/.local/share/containers
chown podman:podman -R /home/podman

EOR

VOLUME /var/lib/containers
VOLUME /home/podman/.local/share/containers

ENV BUILDAH_ISOLATION=chroot
